{
 "title": "Pink Coffee - Sakuli POC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Test execution durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "case_000_Pink_Coffee_duration_seconds",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Errors over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "case_000_Pink_Coffee_error{job=\"pink-coffee\", step=~\"[0-9]{3}_.+\"}",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Failing steps",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "case_000_Pink_Coffee_error{job=\"pink-coffee\", step=~\"[0-9]{3}_.+\"}",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Pink coffee uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum((count_over_time(case_000_Pink_Coffee_error{job=\"pink-coffee\", step=~\"[0-9]{3}_.+\"}[1d])-sum_over_time(case_000_Pink_Coffee_error{job=\"pink-coffee\", step=~\"[0-9]{3}_.+\"}[1d]))/count_over_time(case_000_Pink_Coffee_error{job=\"pink-coffee\", step=~\"[0-9]{3}_.+\"}[1d]))/count(case_000_Pink_Coffee_error{job=\"pink-coffee\", step=~\"[0-9]{3}_.+\"})"
    }
   ]
  }
 ]
}