name: Build-release

on:
  push:
    tags:
      - v*.*.*
    branches: [master]

jobs:
  release-tag-build:
    name: release-tag-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set DASHBOARD_VERSION according to pushed tag
        run: echo ::set-env name=DASHBOARD_VERSION::${GITHUB_REF#refs/*/}
      - name: Show new release version
        run: echo DASHBOARD_VERSION=${DASHBOARD_VERSION}
#      - name: Build Docker image
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: taconsol/sakuli-dashboard
#          tags: $DASHBOARD_VERSION
